<?php 


	var $respuesta = '[{"ID_CAUSA":"1","CAUSA":"FALTA DE MATERIAL"},
{"ID_CAUSA":"2","CAUSA":"FALTA DE MATERIAL PRENSAS"},
{"ID_CAUSA":"3","CAUSA":"FALTA DE MATERIAL BRAZIN"},
{"ID_CAUSA":"4","CAUSA":"FALTA DE MATERIAL MAQUINADOS"},
{"ID_CAUSA":"5","CAUSA":"FALTA DE MATERIAL BONDING"},
{"ID_CAUSA":"6","CAUSA":"FALTA DE MATERIAL ENSAMBLE"},
{"ID_CAUSA":"7","CAUSA":"FALTA DE MATERIAL CALIDAD"},
{"ID_CAUSA":"8","CAUSA":"FALTA DE LUBRICACION"},
{"ID_CAUSA":"9","CAUSA":"FALLA DE AIRE"},
{"ID_CAUSA":"10","CAUSA":"FALLA HIDRAULICA"},
{"ID_CAUSA":"11","CAUSA":"FALLA MECANICA"},
{"ID_CAUSA":"12","CAUSA":"FALLA ELECTRICA O DE CORRIENTE"},
{"ID_CAUSA":"13","CAUSA":"MANTENIMIENTO PREVENTIVO"},
{"ID_CAUSA":"14","CAUSA":"HERRAMENTAL DANADO"},
{"ID_CAUSA":"15","CAUSA":"AJUSTE POR OPERADOR"},
{"ID_CAUSA":"16","CAUSA":"SOBRE-PRODUCCION"}]';


	var $hola = 10;


 ?>


